### ISSUE TITLE
Discord link expired

### ISSUE THREAD

**Issue by cynicallyconsistent** [ColonolNutty/s4cl-template-project#2]
Hello, your discord invite link in the README.md file has expired. Could you please update it so I can join the server?

**Comment by ColonolNutty** [comment]
It is now updated.

**Comment by sv-g** [comment]
hi ! hope this isn't annoying but its not working again :(((

**Comment by ColonolNutty** [comment]
What isn't working? The discord link? I haven't touched any discord links.

**Comment by sv-g** [comment]
nm my account was buggy :) thanks
